### PR TITLE
feat: handle invalid xml characters

### PR DESCRIPTION
**Pull request by NikiforovAll**
This pull request includes several changes to the `Clippit.Tests/Excel/Samples/SpreadsheetWriterSamples.cs` and `Clippit/Excel/SpreadsheetWriter.cs` files to improve code readability, initialization, and XML handling. The most important changes include the removal of unnecessary `using` statements, the conversion of array initializations to collection initializations, and the addition of a method to sanitize XML strings.

Code readability and initialization improvements:

* [`Clippit.Tests/Excel/Samples/SpreadsheetWriterSamples.cs`](diffhunk://#diff-04d53deef0831bdb2ff42312ff70aac03875fc7f4b55a4d6747ff0deac82c106L1-R21): Removed unnecessary `using` statements and converted array initializations to collection initializations in `Sample1` and `Sample2` methods. [[1]](diffhunk://#diff-04d53deef0831bdb2ff42312ff70aac03875fc7f4b55a4d6747ff0deac82c106L1-R21) [[2]](diffhunk://#diff-04d53deef0831bdb2ff42312ff70aac03875fc7f4b55a4d6747ff0deac82c106L40-R41) [[3]](diffhunk://#diff-04d53deef0831bdb2ff42312ff70aac03875fc7f4b55a4d6747ff0deac82c106L55-R55) [[4]](diffhunk://#diff-04d53deef0831bdb2ff42312ff70aac03875fc7f4b55a4d6747ff0deac82c106R64-R68) [[5]](diffhunk://#diff-04d53deef0831bdb2ff42312ff70aac03875fc7f4b55a4d6747ff0deac82c106L86-R194) [[6]](diffhunk://#diff-04d53deef0831bdb2ff42312ff70aac03875fc7f4b55a4d6747ff0deac82c106R209-R249)

XML handling improvements:

* [`Clippit/Excel/SpreadsheetWriter.cs`](diffhunk://#diff-88509055f71125aab61f6d7b2755b6d328ea4785fd885da425c6036988b095f8L6-R7): Removed unnecessary `using` statements and added `using System.Globalization` and `using System.Text`.
* [`Clippit/Excel/SpreadsheetWriter.cs`](diffhunk://#diff-88509055f71125aab61f6d7b2755b6d328ea4785fd885da425c6036988b095f8L26-R24): Initialized `Worksheets` property with an empty collection in `WorkbookDfn` class.
* [`Clippit/Excel/SpreadsheetWriter.cs`](diffhunk://#diff-88509055f71125aab61f6d7b2755b6d328ea4785fd885da425c6036988b095f8L461-R473): Modified date and time formatting to use `CultureInfo.InvariantCulture` in the `out int numColumns` method.
* [`Clippit/Excel/SpreadsheetWriter.cs`](diffhunk://#diff-88509055f71125aab61f6d7b2755b6d328ea4785fd885da425c6036988b095f8R691-R714): Added `SanitizeXmlString` method to handle invalid XML characters.

### CODE REVIEW

**Comment by NikiforovAll** [comment]
FYI:  for some reason I can't build the project with `9.0.100`, it takes ages to build. I guess it happens only on my machine

**Comment by sergey-tihon** [comment]
1. Please take a look at failed build
2. Copilot found typos in the code and propose some nice suggestions 
image

3. Why do we need to introduce option and choose between exception and removal? Why we cannot properly encode invalid symbols and keep them in Excel?

```csharp
private static string SanitizeXmlString(string? xml)
{
    if (string.IsNullOrEmpty(xml))
    {
        return string.Empty;
    }

    var buffer = new StringBuilder(xml.Length);

    foreach (var c in xml)
    {
        if (XmlConvert.IsXmlChar(c))
        {
            buffer.Append(c);
        }
        else
        {
            buffer.AppendFormat("&#x{0:X};", (int)c); // Encode invalid characters
        }
    }

    return buffer.ToString();
}
```

**Comment by NikiforovAll** [comment]
How did you generate copilot suggestions?

**Comment by sergey-tihon** [comment]
> How did you generate copilot suggestions?

I have Copilot integrated into GitHub
https://docs.github.com/en/enterprise-cloud@latest/copilot/using-github-copilot/asking-github-copilot-questions-in-github

**Comment by NikiforovAll** [comment]
I actually, have it too. Thank you for the tip

**Pull request merged**
