### PR TITLE
remove caracters to prevent > at document assembler

### PR DESCRIPTION
**Pull request by luizfbicalho**
In some cases I have page breaks or line breaks between the assembly and I get this issue
image

### CODE REVIEW

**Comment by sergey-tihon** [comment]
@luizfbicalho can you please explain why this change actually fix the issue? (it looks very magical 😁)

Or/better add simple test that reproduce this behavior without this change.

**Comment by luizfbicalho** [comment]
> @luizfbicalho can you please explain why this change actually fix the issue? (it looks very magical 😁)
> 
> Or/better add simple test that reproduce this behavior without this change.

In some cases, there is one character in the middle of the replace that is a line break or a page break, and this character doesn't add 1 to the lenth of the string, this way the replaced string is one string smaller than the template string and when the replace 
happens, one ">" remains on the result document, I'll try to create a test here

**Comment by luizfbicalho** [comment]
Now I have different results in OpenXmlPowerTools and in Clippit
[correct.docx](https://github.com/sergey-tihon/Clippit/files/9570237/correct.docx)
[error.docx](https://github.com/sergey-tihon/Clippit/files/9570239/error.docx)

But the  clippit result in test doesn't have the > charactere in the error.docx
any idea whats going on?

[DA-TemplateMaior-processed-by-DocumentAssembler.docx](https://github.com/sergey-tihon/Clippit/files/9570252/DA-TemplateMaior-processed-by-DocumentAssembler.docx)

The test is the DA-templateMaior.docx and DA-templateMaior.xml, if you run them on old power tools you get the > 


The element that I'm filtering is this

```xml
<r xmlns="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <lastRenderedPageBreak />
</r>
```

this element in this code has the Ch property as null or empty


```C#
var charsAndRuns = runsTrimmed
    .Select(r => new { Ch = UnicodeMapper.RunToString(r), r })
    //.Where(w => !string.IsNullOrEmpty(w.Ch))
    .ToList();
```

but for some reason this element doesn't appear on the list.

**Comment by luizfbicalho** [comment]
This Is solved by the #58  PR

**Pull request closed without merging**
