### PR TITLE
 DocumentAssembler: Support for images

### PR DESCRIPTION
**Pull request by michha**
In our organisation we use a custom Clippit version, where we took a [Pull Request for the Open-Xml-PowerTools](https://github.com/EricWhiteDev/Open-Xml-PowerTools/pull/30/commits) and applied it on Clippit.
I want to bring this feature to Clippit, so everyone can use it.

### CODE REVIEW

**Comment by sergey-tihon** [comment]
Thank you for  this PR @michha !

Can you please briefly describe the feature here or add new [docs page](https://github.com/sergey-tihon/Clippit/tree/master/docs/Word) if it bring new API/capability. I do my best to document all significant changes.

**Comment by michha** [comment]
First I want to line out, that this contribution is not our own but from user @krembf that he tried to get into the Microsoft repo back in 2018 (see [DocumentAssembler: Support for Images (#42) #236](https://github.com/OfficeDev/Open-Xml-PowerTools/pull/236)).
In December 2020 user @carzaza tried to get this changes into the fork from Eric White (see [DocumentAssembler: Support for images #30](https://github.com/EricWhiteDev/Open-Xml-PowerTools/pull/30)).

Because of holidays it will take me some weeks to get a new docs page.

**Comment by sergey-tihon** [comment]
I've released code from this branch in [v1.7.0-beta1](https://www.nuget.org/packages/Clippit/1.7.0-beta1)
@michha can you please try it and confirm that it works for you?

**Comment by krembf** [comment]
Thanks for mentioning me, @michha!
In case this would be of any help with documentation, I'm attaching some details of the implementation (extracted from the conversation I had with the original owner of the PowerTools.
[SupportForImages.docx](https://github.com/sergey-tihon/Clippit/files/6766223/SupportForImages.docx)

**Comment by michha** [comment]
> I've released code from this branch in [v1.7.0-beta1](https://www.nuget.org/packages/Clippit/1.7.0-beta1)
> @michha can you please try it and confirm that it works for you?

Our use cases are working with the beta release 👍

**Comment by sergey-tihon** [comment]
I've released it as [v1.7.0](https://www.nuget.org/packages/Clippit/1.7.0) but it will be nice to add more docs for this as separate PR.

**Pull request merged**
